export const enum QuestionSectionIdentifier {
  CONSENT_FORM,
  FAMILY_AFFECTED,
  FAMILY_BREAST,
  FAMILY_OVARIAN,
  FAMILY_AFFECTED_GRANDMOTHER,
  FAMILY_AFFECTED_AUNT,
  FAMILY_AFFECTED_NIECE,
  FAMILY_AFFECTED_HALF_SISTER,
  PERSONAL_HISTORY
}
