package uk.ac.herc.bcra.domain.enumeration;

/**
 * The QuestionGroupIdentifier enumeration.
 */
public enum QuestionGroupIdentifier {
    CONSENT_FORM_QUESTIONS, FAMILY_BREAST_AFFECTED_QUESTIONS, FAMILY_BREAST_HOW_MANY_QUESTIONS, FAMILY_BREAST_AGE_QUESTIONS, FAMILY_OVARIAN_AFFECTED_QUESTIONS, FAMILY_OVARIAN_HOW_MANY_QUESTIONS, FAMILY_OVARIAN_AGE_QUESTIONS, FAMILY_AFFECTED_GRANDMOTHER_QUESTIONS, FAMILY_AFFECTED_AUNT_QUESTIONS, FAMILY_AFFECTED_NIECE_QUESTIONS, FAMILY_AFFECTED_HALF_SISTER_QUESTIONS, PERSONAL_HISTORY_QUESTIONS, MALE_BREAST_CANCER_QUESTIONS
}
