package uk.ac.herc.bcra.domain.enumeration;

/**
 * The QuestionSectionIdentifier enumeration.
 */
public enum QuestionSectionIdentifier {
    CONSENT_FORM, FAMILY_BREAST_AFFECTED, FAMILY_BREAST_HOW_MANY, FAMILY_BREAST_AGE, FAMILY_OVARIAN_AFFECTED, FAMILY_OVARIAN_HOW_MANY, FAMILY_OVARIAN_AGE, FAMILY_AFFECTED_GRANDMOTHER, FAMILY_AFFECTED_AUNT, FAMILY_AFFECTED_NIECE, FAMILY_AFFECTED_HALF_SISTER, PERSONAL_HISTORY, MALE_BREAST_CANCER
}
