package uk.ac.herc.bcra.domain.enumeration;

/**
 * The QuestionIdentifier enumeration.
 */
public enum QuestionIdentifier {
    SELF_FIRST_PERIOD, SELF_PREMENOPAUSAL, SELF_MENOPAUSAL_AGE, SELF_PREGNANCIES, SELF_PREGNANCY_FIRST_AGE, SELF_HEIGHT, SELF_WEIGHT, SELF_BREAST_BIOPSY, SELF_BREAST_BIOPSY_DIAGNOSIS_RISK, SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES, SELF_ASHKENAZI, FAMILY_BLOOD_RELATIVES, FAMILY_MATERNAL_RELATIVES, FAMILY_PATERNAL_RELATIVES, RELATIVE_HOW_MANY, RELATIVE_DIAGNOSIS, RELATIVE_FIRST_DIAGNOSIS_AGE, RELATIVE_SECOND_DIAGNOSIS_AGE, RELATIVE_GENETIC_TESTING, RELATIVE_GENETIC_TESTING_RESULT, RELATIVE_OVARIAN_CANCER, RELATIVE_OVARIAN_CANCER_AGE, FATHER_BREAST_CANCER, BROTHER_BREAST_CANCER
}
