package uk.ac.herc.bcra.domain.enumeration;

/**
 * The QuestionSectionIdentifier enumeration.
 */
public enum QuestionSectionIdentifier {
    PERSONAL_HISTORY, FAMILY_HISTORY, MOTHER, SISTER_COUNT, SISTERS, NIECE_COUNT, NIECES, MATERNAL_HALF_SISTER_COUNT, MATERNAL_HALF_SISTERS, MATERNAL_GRANDMOTHER, MATERNAL_AUNT_COUNT, MATERNAL_AUNTS, MATERNAL_COUSIN_COUNT, MATERNAL_COUSINS, PATERNAL_HALF_SISTER_COUNT, PATERNAL_HALF_SISTERS, PATERNAL_GRANDMOTHER, PATERNAL_AUNT_COUNT, PATERNAL_AUNTS, PATERNAL_COUSIN_COUNT, PATERNAL_COUSINS, MALE_BREAST_CANCER
}
