package uk.ac.herc.bcra.domain.enumeration;

/**
 * The QuestionSectionIdentifier enumeration.
 */
public enum QuestionSectionIdentifier {
    CONSENT_FORM, FAMILY_AFFECTED, FAMILY_BREAST, FAMILY_OVARIAN, FAMILY_AFFECTED_GRANDMOTHER, FAMILY_AFFECTED_AUNT, FAMILY_AFFECTED_NIECE, FAMILY_AFFECTED_HALF_SISTER, PERSONAL_HISTORY, FAMILY_AFFECTED_CONTEXT, PERSONAL_HISTORY_CONTEXT
}
