package uk.ac.herc.bcra.domain.enumeration;

/**
 * The QuestionGroupIdentifier enumeration.
 */
public enum QuestionGroupIdentifier {
    CONSENT_FORM_QUESTIONS, FAMILY_AFFECTED_QUESTIONS, FAMILY_BREAST_QUESTIONS, FAMILY_OVARIAN_QUESTIONS, FAMILY_AFFECTED_GRANDMOTHER_QUESTIONS, FAMILY_AFFECTED_AUNT_QUESTIONS, FAMILY_AFFECTED_NIECE_QUESTIONS, FAMILY_AFFECTED_HALF_SISTER_QUESTIONS, PERSONAL_HISTORY_QUESTIONS, FAMILY_AFFECTED_CONTEXT_PLACEHOLDER, PERSONAL_HISTORY_CONTEXT_PLACEHOLDER
}
