export const enum DisplayConditionType {
  DISPLAY_SECTION_CONDITION_QUESTION = 'DISPLAY_SECTION_CONDITION_QUESTION',
  DISPLAY_QUESTION_CONDITION_QUESTION = 'DISPLAY_QUESTION_CONDITION_QUESTION',
  DISPLAY_SECTION_CONDITION_ITEM = 'DISPLAY_SECTION_CONDITION_ITEM',
  DISPLAY_QUESTION_CONDITION_ITEM = 'DISPLAY_QUESTION_CONDITION_ITEM'
}

export const enum QuestionSectionIdentifier {
  PERSONAL_HISTORY = 'PERSONAL_HISTORY',
  FAMILY_HISTORY = 'FAMILY_HISTORY',
  MOTHER = 'MOTHER',
  SISTER_COUNT = 'SISTER_COUNT',
  SISTERS = 'SISTERS',
  NIECE_COUNT = 'NIECE_COUNT',
  NIECES = 'NIECES',
  MATERNAL_HALF_SISTER_COUNT = 'MATERNAL_HALF_SISTER_COUNT',
  MATERNAL_HALF_SISTERS = 'MATERNAL_HALF_SISTERS',
  MATERNAL_GRANDMOTHER = 'MATERNAL_GRANDMOTHER',
  MATERNAL_AUNT_COUNT = 'MATERNAL_AUNT_COUNT',
  MATERNAL_AUNTS = 'MATERNAL_AUNTS',
  MATERNAL_COUSIN_COUNT = 'MATERNAL_COUSIN_COUNT',
  MATERNAL_COUSINS = 'MATERNAL_COUSINS',
  PATERNAL_HALF_SISTER_COUNT = 'PATERNAL_HALF_SISTER_COUNT',
  PATERNAL_HALF_SISTERS = 'PATERNAL_HALF_SISTERS',
  PATERNAL_GRANDMOTHER = 'PATERNAL_GRANDMOTHER',
  PATERNAL_AUNT_COUNT = 'PATERNAL_AUNT_COUNT',
  PATERNAL_AUNTS = 'PATERNAL_AUNTS',
  PATERNAL_COUSIN_COUNT = 'PATERNAL_COUSIN_COUNT',
  PATERNAL_COUSINS = 'PATERNAL_COUSINS',
  MALE_BREAST_CANCER = 'MALE_BREAST_CANCER'
}

export const enum QuestionIdentifier {
  SELF_FIRST_PERIOD = 'SELF_FIRST_PERIOD',
  SELF_PREMENOPAUSAL = 'SELF_PREMENOPAUSAL',
  SELF_MENOPAUSAL_AGE = 'SELF_MENOPAUSAL_AGE',
  SELF_PREGNANCIES = 'SELF_PREGNANCIES',
  SELF_PREGNANCY_FIRST_AGE = 'SELF_PREGNANCY_FIRST_AGE',
  SELF_HEIGHT = 'SELF_HEIGHT',
  SELF_WEIGHT = 'SELF_WEIGHT',
  SELF_BREAST_BIOPSY = 'SELF_BREAST_BIOPSY',
  SELF_BREAST_BIOPSY_DIAGNOSIS_RISK = 'SELF_BREAST_BIOPSY_DIAGNOSIS_RISK',
  SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES = 'SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES',
  SELF_ASHKENAZI = 'SELF_ASHKENAZI',
  FAMILY_BLOOD_RELATIVES = 'FAMILY_BLOOD_RELATIVES',
  FAMILY_MATERNAL_RELATIVES = 'FAMILY_MATERNAL_RELATIVES',
  FAMILY_PATERNAL_RELATIVES = 'FAMILY_PATERNAL_RELATIVES',
  RELATIVE_HOW_MANY = 'RELATIVE_HOW_MANY',
  RELATIVE_DIAGNOSIS = 'RELATIVE_DIAGNOSIS',
  RELATIVE_FIRST_DIAGNOSIS_AGE = 'RELATIVE_FIRST_DIAGNOSIS_AGE',
  RELATIVE_SECOND_DIAGNOSIS_AGE = 'RELATIVE_SECOND_DIAGNOSIS_AGE',
  RELATIVE_GENETIC_TESTING = 'RELATIVE_GENETIC_TESTING',
  RELATIVE_GENETIC_TESTING_RESULT = 'RELATIVE_GENETIC_TESTING_RESULT',
  RELATIVE_OVARIAN_CANCER = 'RELATIVE_OVARIAN_CANCER',
  RELATIVE_OVARIAN_CANCER_AGE = 'RELATIVE_OVARIAN_CANCER_AGE',
  FATHER_BREAST_CANCER = 'FATHER_BREAST_CANCER',
  BROTHER_BREAST_CANCER = 'BROTHER_BREAST_CANCER'
}

export const enum QuestionItemIdentifier {
  SELF_PREMENOPAUSAL_YES = 'SELF_PREMENOPAUSAL_YES',
  SELF_PREMENOPAUSAL_NO = 'SELF_PREMENOPAUSAL_NO',
  SELF_PREMENOPAUSAL_UNKNOWN = 'SELF_PREMENOPAUSAL_UNKNOWN',
  SELF_BREAST_BIOPSY_YES = 'SELF_BREAST_BIOPSY_YES',
  SELF_BREAST_BIOPSY_NO = 'SELF_BREAST_BIOPSY_NO',
  SELF_BREAST_BIOPSY_UNKNOWN = 'SELF_BREAST_BIOPSY_UNKNOWN',
  SELF_BREAST_BIOPSY_DIAGNOSIS_RISK_YES = 'SELF_BREAST_BIOPSY_DIAGNOSIS_RISK_YES',
  SELF_BREAST_BIOPSY_DIAGNOSIS_RISK_NO = 'SELF_BREAST_BIOPSY_DIAGNOSIS_RISK_NO',
  SELF_BREAST_BIOPSY_DIAGNOSIS_RISK_UNKNOWN = 'SELF_BREAST_BIOPSY_DIAGNOSIS_RISK_UNKNOWN',
  SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_ADH = 'SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_ADH',
  SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_LCIS = 'SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_LCIS',
  SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_ALH = 'SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_ALH',
  SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_OTHER = 'SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_OTHER',
  SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_FORGOT = 'SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_FORGOT',
  SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_UNKNOWN = 'SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_UNKNOWN',
  SELF_ASHKENAZI_YES = 'SELF_ASHKENAZI_YES',
  SELF_ASHKENAZI_NO = 'SELF_ASHKENAZI_NO',
  SELF_ASHKENAZI_UNKNOWN = 'SELF_ASHKENAZI_UNKNOWN',
  FAMILY_BLOOD_RELATIVES_MOTHER = 'FAMILY_BLOOD_RELATIVES_MOTHER',
  FAMILY_BLOOD_RELATIVES_SISTERS = 'FAMILY_BLOOD_RELATIVES_SISTERS',
  FAMILY_BLOOD_RELATIVES_NIECES = 'FAMILY_BLOOD_RELATIVES_NIECES',
  FAMILY_MATERNAL_RELATIVES_HALF_SISTERS = 'FAMILY_MATERNAL_RELATIVES_HALF_SISTERS',
  FAMILY_MATERNAL_RELATIVES_GRANDMOTHER = 'FAMILY_MATERNAL_RELATIVES_GRANDMOTHER',
  FAMILY_MATERNAL_RELATIVES_AUNTS = 'FAMILY_MATERNAL_RELATIVES_AUNTS',
  FAMILY_MATERNAL_RELATIVES_COUSINS = 'FAMILY_MATERNAL_RELATIVES_COUSINS',
  FAMILY_PATERNAL_RELATIVES_HALF_SISTERS = 'FAMILY_PATERNAL_RELATIVES_HALF_SISTERS',
  FAMILY_PATERNAL_RELATIVES_GRANDMOTHER = 'FAMILY_PATERNAL_RELATIVES_GRANDMOTHER',
  FAMILY_PATERNAL_RELATIVES_AUNTS = 'FAMILY_PATERNAL_RELATIVES_AUNTS',
  FAMILY_PATERNAL_RELATIVES_COUSINS = 'FAMILY_PATERNAL_RELATIVES_COUSINS',
  RELATIVE_DIAGNOSIS_UNILATERAL = 'RELATIVE_DIAGNOSIS_UNILATERAL',
  RELATIVE_DIAGNOSIS_BILATERAL = 'RELATIVE_DIAGNOSIS_BILATERAL',
  RELATIVE_DIAGNOSIS_UNKNOWN = 'RELATIVE_DIAGNOSIS_UNKNOWN',
  RELATIVE_GENETIC_TESTING_YES = 'RELATIVE_GENETIC_TESTING_YES',
  RELATIVE_GENETIC_TESTING_NO = 'RELATIVE_GENETIC_TESTING_NO',
  RELATIVE_GENETIC_TESTING_UNKNOWN = 'RELATIVE_GENETIC_TESTING_UNKNOWN',
  RELATIVE_GENETIC_TESTING_RESULT_BRCA1 = 'RELATIVE_GENETIC_TESTING_RESULT_BRCA1',
  RELATIVE_GENETIC_TESTING_RESULT_BRCA2 = 'RELATIVE_GENETIC_TESTING_RESULT_BRCA2',
  RELATIVE_GENETIC_TESTING_RESULT_NONE = 'RELATIVE_GENETIC_TESTING_RESULT_NONE',
  RELATIVE_GENETIC_TESTING_RESULT_UNKNOWN = 'RELATIVE_GENETIC_TESTING_RESULT_UNKNOWN'
}

export interface IDisplayCondition {
  id?: number;
  displayConditionType?: DisplayConditionType;
  conditionSectionIdentifier?: QuestionSectionIdentifier;
  conditionQuestionIdentifier?: QuestionIdentifier;
  conditionQuestionItemIdentifier?: QuestionItemIdentifier;
  displayQuestionSectionId?: number;
  displayQuestionId?: number;
}

export class DisplayCondition implements IDisplayCondition {
  constructor(
    public id?: number,
    public displayConditionType?: DisplayConditionType,
    public conditionSectionIdentifier?: QuestionSectionIdentifier,
    public conditionQuestionIdentifier?: QuestionIdentifier,
    public conditionQuestionItemIdentifier?: QuestionItemIdentifier,
    public displayQuestionSectionId?: number,
    public displayQuestionId?: number
  ) {}
}
