export const enum QuestionItemIdentifier {
  CONSENT_INFO_SHEET_YES = 'CONSENT_INFO_SHEET_YES',
  CONSENT_INFO_SHEET_NO = 'CONSENT_INFO_SHEET_NO',
  CONSENT_FUTURE_RESEARCH_YES = 'CONSENT_FUTURE_RESEARCH_YES',
  CONSENT_FUTURE_RESEARCH_NO = 'CONSENT_FUTURE_RESEARCH_NO',
  FAMILY_BREAST_AFFECTED_MOTHER = 'FAMILY_BREAST_AFFECTED_MOTHER',
  FAMILY_BREAST_AFFECTED_GRANDMOTHER = 'FAMILY_BREAST_AFFECTED_GRANDMOTHER',
  FAMILY_BREAST_AFFECTED_SISTER = 'FAMILY_BREAST_AFFECTED_SISTER',
  FAMILY_BREAST_AFFECTED_HALFSISTER = 'FAMILY_BREAST_AFFECTED_HALFSISTER',
  FAMILY_BREAST_AFFECTED_AUNT = 'FAMILY_BREAST_AFFECTED_AUNT',
  FAMILY_BREAST_AFFECTED_NIECE = 'FAMILY_BREAST_AFFECTED_NIECE',
  FAMILY_BREAST_AFFECTED_FATHER = 'FAMILY_BREAST_AFFECTED_FATHER',
  FAMILY_BREAST_AFFECTED_BROTHER = 'FAMILY_BREAST_AFFECTED_BROTHER',
  FAMILY_BREAST_AFFECTED_UNKNOWN = 'FAMILY_BREAST_AFFECTED_UNKNOWN',
  FAMILY_BREAST_HOW_MANY_ONE = 'FAMILY_BREAST_HOW_MANY_ONE',
  FAMILY_BREAST_HOW_MANY_MORE = 'FAMILY_BREAST_HOW_MANY_MORE',
  FAMILY_OVARIAN_AFFECTED_MOTHER = 'FAMILY_OVARIAN_AFFECTED_MOTHER',
  FAMILY_OVARIAN_AFFECTED_GRANDMOTHER = 'FAMILY_OVARIAN_AFFECTED_GRANDMOTHER',
  FAMILY_OVARIAN_AFFECTED_SISTER = 'FAMILY_OVARIAN_AFFECTED_SISTER',
  FAMILY_OVARIAN_AFFECTED_HALFSISTER = 'FAMILY_OVARIAN_AFFECTED_HALFSISTER',
  FAMILY_OVARIAN_AFFECTED_AUNT = 'FAMILY_OVARIAN_AFFECTED_AUNT',
  FAMILY_OVARIAN_AFFECTED_NIECE = 'FAMILY_OVARIAN_AFFECTED_NIECE',
  FAMILY_OVARIAN_AFFECTED_UNKNOWN = 'FAMILY_OVARIAN_AFFECTED_UNKNOWN',
  FAMILY_OVARIAN_HOW_MANY_ONE = 'FAMILY_OVARIAN_HOW_MANY_ONE',
  FAMILY_OVARIAN_HOW_MANY_MORE = 'FAMILY_OVARIAN_HOW_MANY_MORE',
  FAMILY_AFFECTED_GRANDMOTHER_SIDE_MOTHER = 'FAMILY_AFFECTED_GRANDMOTHER_SIDE_MOTHER',
  FAMILY_AFFECTED_GRANDMOTHER_SIDE_FATHER = 'FAMILY_AFFECTED_GRANDMOTHER_SIDE_FATHER',
  FAMILY_AFFECTED_AUNT_SIDE_MOTHER = 'FAMILY_AFFECTED_AUNT_SIDE_MOTHER',
  FAMILY_AFFECTED_AUNT_SIDE_FATHER = 'FAMILY_AFFECTED_AUNT_SIDE_FATHER',
  FAMILY_AFFECTED_NIECE_SIDE_SISTER = 'FAMILY_AFFECTED_NIECE_SIDE_SISTER',
  FAMILY_AFFECTED_NIECE_SIDE_BROTHER = 'FAMILY_AFFECTED_NIECE_SIDE_BROTHER',
  FAMILY_AFFECTED_HALFSISTER_SIDE_MOTHER = 'FAMILY_AFFECTED_HALFSISTER_SIDE_MOTHER',
  FAMILY_AFFECTED_HALFSISTER_SIDE_FATHER = 'FAMILY_AFFECTED_HALFSISTER_SIDE_FATHER',
  SELF_PREMENOPAUSAL_YES = 'SELF_PREMENOPAUSAL_YES',
  SELF_PREMENOPAUSAL_NO = 'SELF_PREMENOPAUSAL_NO',
  SELF_PREMENOPAUSAL_UNKNOWN = 'SELF_PREMENOPAUSAL_UNKNOWN',
  SELF_BREAST_BIOPSY_YES = 'SELF_BREAST_BIOPSY_YES',
  SELF_BREAST_BIOPSY_NO = 'SELF_BREAST_BIOPSY_NO',
  SELF_BREAST_BIOPSY_UNKNOWN = 'SELF_BREAST_BIOPSY_UNKNOWN',
  SELF_BREAST_BIOPSY_DIAGNOSIS_RISK_YES = 'SELF_BREAST_BIOPSY_DIAGNOSIS_RISK_YES',
  SELF_BREAST_BIOPSY_DIAGNOSIS_RISK_NO = 'SELF_BREAST_BIOPSY_DIAGNOSIS_RISK_NO',
  SELF_BREAST_BIOPSY_DIAGNOSIS_RISK_UNKNOWN = 'SELF_BREAST_BIOPSY_DIAGNOSIS_RISK_UNKNOWN',
  SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_ADH = 'SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_ADH',
  SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_LCIS = 'SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_LCIS',
  SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_ALH = 'SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_ALH',
  SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_OTHER = 'SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_OTHER',
  SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_UNKNOWN = 'SELF_BREAST_BIOPSY_DIAGNOSIS_TYPES_UNKNOWN',
  SELF_ASHKENAZI_YES = 'SELF_ASHKENAZI_YES',
  SELF_ASHKENAZI_NO = 'SELF_ASHKENAZI_NO',
  SELF_ASHKENAZI_UNKNOWN = 'SELF_ASHKENAZI_UNKNOWN'
}

export interface IQuestionItem {
  id?: number;
  identifier?: QuestionItemIdentifier;
  order?: number;
  label?: string;
  necessary?: boolean;
  exclusive?: boolean;
  questionId?: number;
}

export class QuestionItem implements IQuestionItem {
  constructor(
    public id?: number,
    public identifier?: QuestionItemIdentifier,
    public order?: number,
    public label?: string,
    public necessary?: boolean,
    public exclusive?: boolean,
    public questionId?: number
  ) {
    this.necessary = this.necessary || false;
    this.exclusive = this.exclusive || false;
  }
}
